title: Your awesome title
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 I'm glad you are here. I plan to talk about my accomplishements. I have 2x Student of the Month 2 , Middlesex County princapls assocaiton outsatnding student award recipet and 2x student role model.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
